import type { AstroComponentFactory } from 'astro/runtime/server/index.js'

import MaternalMortalityInequity from '@/components/suicide-mortality/MaternalMortalityInequity.astro'
import Analytics from '@/components/analytics/Analytics.astro'
import Welcome from '@/components/Welcome.astro'
import MaternalMortalitySDoH from '@/components/suicide-mortality/MaternalMortalitySDoH.astro'
import PrioritySelector from '@/components/PrioritySelector.astro'
import StratifiedIndicator from '@/components/StratifiedIndicator.astro'

import type {
  MaternalMortalityRateRow,
  ForestPlotDataRow,
  AnalyticsMaternalRow,
  ScatterMaternalRow,
  StratifiedRow,
} from '@/lib/parquet'
import type { IndicatorStratifier } from '@/lib/indicators'

export interface PageProps {
  title: string
  text: string
  dimension?: string
  subdimensions?: string[]
  pages: unknown[]
  slug: string | undefined
  date: Date
  source?: string
  data?: MaternalMortalityRateRow[]
  forestPlotData?: ForestPlotDataRow[]
  analyticsMaternalData?: AnalyticsMaternalRow[]
  scatterMaternalData?: ScatterMaternalRow[]
  trasladoData?: StratifiedRow[]
  frecuenciaTransporteData?: StratifiedRow[]
  sobrecargaCuidadosData?: StratifiedRow[]
  empleoInformalData?: StratifiedRow[]
  coberturaProgramaData?: StratifiedRow[]
  controlesPrenatalData?: StratifiedRow[]
  apoyoInfantilData?: StratifiedRow[]
  stratifiers?: IndicatorStratifier[]
}

type PropsResolver = (
  props: PageProps,
  baseUrl: string,
) => Record<string, unknown>

interface PageRegistryEntry {
  component: AstroComponentFactory
  resolveProps: PropsResolver
}

const base = (url: string, path: string) => `${url}/data/${path}`

// Years generated by the R mock scripts (2016–2025).
const STRATIFIED_MOCK_YEARS = [
  2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025,
]

export const pageRegistry: Record<string, PageRegistryEntry> = {
  // ─── No slug (home) ────────────────────────────────────────────────────────
  '': {
    component: Welcome,
    resolveProps: ({ text }) => ({ text }),
  },

  // ─── Section index pages ───────────────────────────────────────────────────
  'analisis-de-inequidad': {
    component: PrioritySelector,
    resolveProps: ({ title, text, slug }) => ({ title, text, section: slug }),
  },
  'determinantes-de-la-salud': {
    component: PrioritySelector,
    resolveProps: ({ title, text, slug }) => ({ title, text, section: slug }),
  },
  analisis: {
    component: PrioritySelector,
    resolveProps: ({ title, text, slug }) => ({ title, text, section: slug }),
  },

  // ─── Detail pages ──────────────────────────────────────────────────────────
  'determinantes-de-la-salud/mortalidad-por-suicidio': {
    component: MaternalMortalitySDoH,
    resolveProps: ({ title, text }) => ({ title, text }),
  },
  'analisis-de-inequidad/mortalidad-por-suicidio': {
    component: MaternalMortalityInequity,
    resolveProps: ({ title, text, data, source }, baseUrl) => ({
      title,
      text,
      data,
      source,
      csvPath: base(baseUrl, 'maternal_mortality_rate.csv'),
    }),
  },
  'analisis/mortalidad-por-suicidio': {
    component: Analytics,
    resolveProps: (
      {
        title,
        text,
        forestPlotData,
        analyticsMaternalData,
        scatterMaternalData,
      },
      baseUrl,
    ) => {
      // Years generated by the R mock scripts (2016–2025).
      // GeoJSONs are generated per-year; the frontend only uses years that
      // appear in the actual data, so extra entries here are harmless.
      const MOCK_YEARS = [
        2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025,
      ]
      const DSS_INDICATORS = [
        'traslado',
        'empleo_informal',
        'sobrecarga',
        'cobertura_programa',
        'transporte',
        'cuidar_comunidad',
      ] as const

      const geojsonUrls = Object.fromEntries(
        DSS_INDICATORS.map((ind) => [
          ind,
          Object.fromEntries(
            MOCK_YEARS.map((yr) => [
              yr,
              base(baseUrl, `mock_bivariate_${ind}_${yr}.geojson`),
            ]),
          ),
        ]),
      ) as Record<string, Record<number, string>>

      const maternalGeojsonUrls = Object.fromEntries(
        MOCK_YEARS.map((yr) => [
          yr,
          base(baseUrl, `mock_maternal_mortality_${yr}.geojson`),
        ]),
      ) as Record<number, string>

      const dssBivariateGeojsonUrls = Object.fromEntries(
        DSS_INDICATORS.map((ind_x) => [
          ind_x,
          Object.fromEntries(
            DSS_INDICATORS.filter((ind_y) => ind_y !== ind_x).map((ind_y) => [
              ind_y,
              Object.fromEntries(
                MOCK_YEARS.map((yr) => [
                  yr,
                  base(
                    baseUrl,
                    `mock_bivariate_dss_${ind_x}_${ind_y}_${yr}.geojson`,
                  ),
                ]),
              ),
            ]),
          ),
        ]),
      )

      return {
        title,
        text,
        forestPlotData,
        analyticsMaternalData,
        scatterMaternalData,
        geojsonUrls,
        maternalGeojsonUrls,
        dssBivariateGeojsonUrls,
        csvUrl: base(baseUrl, 'mock_scatter_maternal.csv'),
      }
    },
  },
  traslado: {
    component: StratifiedIndicator,
    resolveProps: (
      {
        title,
        text,
        dimension,
        subdimensions,
        stratifiers,
        trasladoData,
        source,
      },
      baseUrl,
    ) => ({
      title,
      text,
      dimension,
      source,
      subdimensions: subdimensions ?? [],
      stratifiers: stratifiers ?? [],
      data: trasladoData ?? [],
      yAxisLabel: '% mujeres embarazadas',
      csvPath: base(baseUrl, 'journey_time.csv'),
      geojsonUrls: Object.fromEntries(
        STRATIFIED_MOCK_YEARS.map((yr) => [
          yr,
          base(baseUrl, `mock_traslado_${yr}.geojson`),
        ]),
      ),
    }),
  },
  'frecuencia-transporte': {
    component: StratifiedIndicator,
    resolveProps: (
      {
        title,
        text,
        dimension,
        subdimensions,
        stratifiers,
        frecuenciaTransporteData,
        source,
      },
      baseUrl,
    ) => ({
      title,
      text,
      dimension,
      source,
      subdimensions: subdimensions ?? [],
      stratifiers: stratifiers ?? [],
      data: frecuenciaTransporteData ?? [],
      yAxisLabel: '% población con acceso',
      csvPath: base(baseUrl, 'transport_frequency.csv'),
      geojsonUrls: Object.fromEntries(
        STRATIFIED_MOCK_YEARS.map((yr) => [
          yr,
          base(baseUrl, `mock_transporte_${yr}.geojson`),
        ]),
      ),
    }),
  },
  'sobrecarga-embarazadas': {
    component: StratifiedIndicator,
    resolveProps: (
      {
        title,
        text,
        dimension,
        subdimensions,
        stratifiers,
        sobrecargaCuidadosData,
        source,
      },
      baseUrl,
    ) => ({
      title,
      text,
      dimension,
      source,
      subdimensions: subdimensions ?? [],
      stratifiers: stratifiers ?? [],
      data: sobrecargaCuidadosData ?? [],
      yAxisLabel: '% mujeres embarazadas',
      csvPath: base(baseUrl, 'care_overload_municipal.csv'),
      geojsonUrls: Object.fromEntries(
        STRATIFIED_MOCK_YEARS.map((yr) => [
          yr,
          base(baseUrl, `mock_sobrecarga_${yr}.geojson`),
        ]),
      ),
    }),
  },
  'embarazadas-empleo-informal': {
    component: StratifiedIndicator,
    resolveProps: (
      {
        title,
        text,
        dimension,
        subdimensions,
        stratifiers,
        empleoInformalData,
        source,
      },
      baseUrl,
    ) => ({
      title,
      text,
      dimension,
      source,
      subdimensions: subdimensions ?? [],
      stratifiers: stratifiers ?? [],
      data: empleoInformalData ?? [],
      yAxisLabel: '% personas con empleo informal',
      csvPath: base(baseUrl, 'informal_employment.csv'),
      geojsonUrls: Object.fromEntries(
        STRATIFIED_MOCK_YEARS.map((yr) => [
          yr,
          base(baseUrl, `mock_empleo_informal_${yr}.geojson`),
        ]),
      ),
    }),
  },
  'apoyo-embarazadas': {
    component: StratifiedIndicator,
    resolveProps: (
      {
        title,
        text,
        dimension,
        subdimensions,
        stratifiers,
        coberturaProgramaData,
        source,
      },
      baseUrl,
    ) => ({
      title,
      text,
      dimension,
      source,
      subdimensions: subdimensions ?? [],
      stratifiers: stratifiers ?? [],
      data: coberturaProgramaData ?? [],
      yAxisLabel: '% mujeres embarazadas',
      csvPath: base(baseUrl, 'program_cover.csv'),
      geojsonUrls: Object.fromEntries(
        STRATIFIED_MOCK_YEARS.map((yr) => [
          yr,
          base(baseUrl, `mock_cobertura_programa_${yr}.geojson`),
        ]),
      ),
    }),
  },
  'apoyo-infantil': {
    component: StratifiedIndicator,
    resolveProps: (
      {
        title,
        text,
        dimension,
        subdimensions,
        stratifiers,
        apoyoInfantilData,
        source,
      },
      baseUrl,
    ) => ({
      title,
      text,
      dimension,
      source,
      subdimensions: subdimensions ?? [],
      stratifiers: stratifiers ?? [],
      data: apoyoInfantilData ?? [],
      yAxisLabel: '% mujeres embarazadas',
      csvPath: base(baseUrl, 'infant_care_support.csv'),
      geojsonUrls: Object.fromEntries(
        STRATIFIED_MOCK_YEARS.map((yr) => [
          yr,
          base(baseUrl, `mock_cuidar_comunidad_${yr}.geojson`),
        ]),
      ),
    }),
  },
}
