import type { AstroComponentFactory } from 'astro/runtime/server/index.js'

import SuicideMortalityInequity from '@/components/suicide-mortality/SuicideMortalityInequity.astro'
import Analytics from '@/components/analytics/Analytics.astro'
import Welcome from '@/components/Welcome.astro'
import SuicideMortalitySDoH from '@/components/suicide-mortality/SuicideMortalitySDoH.astro'
import PrioritySelector from '@/components/PrioritySelector.astro'
import DSSIndicator from '@/components/indicators/DSSIndicator.astro'
import StratifiedIndicator from '@/components/indicators/StratifiedIndicator.astro'

import type {
  SuicideMortalityRateRow,
  ForestPlotDataRow,
  AnalyticsSuicideRow,
  ScatterSuicideRow,
  SimpleRow,
  StratifiedRow,
} from '@/lib/parquet'

export interface PageProps {
  title: string
  text: string
  dimension?: string
  subdimensions?: string[]
  pages: unknown[]
  slug: string | undefined
  date: Date
  source?: string
  data?: SuicideMortalityRateRow[]
  forestPlotData?: ForestPlotDataRow[]
  analyticsSuicideData?: AnalyticsSuicideRow[]
  scatterSuicideData?: ScatterSuicideRow[]
  aprobacionData?: SimpleRow[]
  reprobacionData?: SimpleRow[]
  coberturaBrutaData?: SimpleRow[]
  coberturaNetaData?: SimpleRow[]
  desercionData?: SimpleRow[]
  repitenciaData?: SimpleRow[]
  previsionSocialData?: StratifiedRow[]
}

type PropsResolver = (
  props: PageProps,
  baseUrl: string,
) => Record<string, unknown>

interface PageRegistryEntry {
  component: AstroComponentFactory
  resolveProps: PropsResolver
}

const base = (url: string, path: string) => `${url}/data/${path}`

const STRATIFIED_YEARS = [
  2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026,
]

export const pageRegistry: Record<string, PageRegistryEntry> = {
  // ─── No slug (home) ────────────────────────────────────────────────────────
  '': {
    component: Welcome,
    resolveProps: ({ text }) => ({ text }),
  },

  // ─── Section index pages ───────────────────────────────────────────────────
  'analisis-de-inequidad': {
    component: PrioritySelector,
    resolveProps: ({ title, text, slug }) => ({ title, text, section: slug }),
  },
  'determinantes-de-la-salud': {
    component: PrioritySelector,
    resolveProps: ({ title, text, slug }) => ({ title, text, section: slug }),
  },
  analisis: {
    component: PrioritySelector,
    resolveProps: ({ title, text, slug }) => ({ title, text, section: slug }),
  },

  // ─── Detail pages ──────────────────────────────────────────────────────────
  'determinantes-de-la-salud/mortalidad-por-suicidio': {
    component: SuicideMortalitySDoH,
    resolveProps: ({ title, text }) => ({ title, text }),
  },
  'analisis-de-inequidad/mortalidad-por-suicidio': {
    component: SuicideMortalityInequity,
    resolveProps: ({ title, text, data, source }, baseUrl) => ({
      title,
      text,
      data,
      source,
      csvPath: base(baseUrl, 'suicide_mortality.csv'),
    }),
  },
  'analisis/mortalidad-por-suicidio': {
    component: Analytics,
    resolveProps: (
      { title, text, forestPlotData, analyticsSuicideData, scatterSuicideData },
      baseUrl,
    ) => {
      // Years generated by the R mock scripts (2016–2025).
      // GeoJSONs are generated per-year; the frontend only uses years that
      // appear in the actual data, so extra entries here are harmless.
      const YEARS = [
        2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026,
      ]
      const DSS_INDICATORS = [
        'traslado',
        'empleo_informal',
        'sobrecarga',
        'cobertura_programa',
        'transporte',
        'cuidar_comunidad',
      ] as const

      const geojsonUrls = Object.fromEntries(
        DSS_INDICATORS.map((ind) => [
          ind,
          Object.fromEntries(
            YEARS.map((yr) => [
              yr,
              base(baseUrl, `mock_bivariate_${ind}_${yr}.geojson`),
            ]),
          ),
        ]),
      ) as Record<string, Record<number, string>>

      const maternalGeojsonUrls = Object.fromEntries(
        YEARS.map((yr) => [
          yr,
          base(baseUrl, `mock_maternal_mortality_${yr}.geojson`),
        ]),
      ) as Record<number, string>

      const dssBivariateGeojsonUrls = Object.fromEntries(
        DSS_INDICATORS.map((ind_x) => [
          ind_x,
          Object.fromEntries(
            DSS_INDICATORS.filter((ind_y) => ind_y !== ind_x).map((ind_y) => [
              ind_y,
              Object.fromEntries(
                YEARS.map((yr) => [
                  yr,
                  base(
                    baseUrl,
                    `mock_bivariate_dss_${ind_x}_${ind_y}_${yr}.geojson`,
                  ),
                ]),
              ),
            ]),
          ),
        ]),
      )

      return {
        title,
        text,
        forestPlotData,
        analyticsSuicideData,
        scatterSuicideData,
        geojsonUrls,
        maternalGeojsonUrls,
        dssBivariateGeojsonUrls,
        csvUrl: base(baseUrl, 'mock_scatter_maternal.csv'),
      }
    },
  },
  aprobacion: {
    component: DSSIndicator,
    resolveProps: (
      { title, text, dimension, subdimensions, aprobacionData, source },
      baseUrl,
    ) => ({
      title,
      text,
      dimension,
      source,
      subdimensions: subdimensions ?? [],
      data: aprobacionData ?? [],
      yAxisLabel: '%',
      csvPath: base(baseUrl, 'education_aprobacion.csv'),
    }),
  },
  reprobacion: {
    component: DSSIndicator,
    resolveProps: (
      { title, text, dimension, subdimensions, reprobacionData, source },
      baseUrl,
    ) => ({
      title,
      text,
      dimension,
      source,
      subdimensions: subdimensions ?? [],
      data: reprobacionData ?? [],
      yAxisLabel: '%',
      csvPath: base(baseUrl, 'education_reprobacion.csv'),
    }),
  },
  cobertura_bruta: {
    component: DSSIndicator,
    resolveProps: (
      { title, text, dimension, subdimensions, coberturaBrutaData, source },
      baseUrl,
    ) => ({
      title,
      text,
      dimension,
      source,
      subdimensions: subdimensions ?? [],
      data: coberturaBrutaData ?? [],
      yAxisLabel: '%',
      csvPath: base(baseUrl, 'education_cobertura_bruta.csv'),
    }),
  },
  cobertura_neta: {
    component: DSSIndicator,
    resolveProps: (
      { title, text, dimension, subdimensions, coberturaNetaData, source },
      baseUrl,
    ) => ({
      title,
      text,
      dimension,
      source,
      subdimensions: subdimensions ?? [],
      data: coberturaNetaData ?? [],
      yAxisLabel: '%',
      csvPath: base(baseUrl, 'education_cobertura_neta.csv'),
    }),
  },
  desercion: {
    component: DSSIndicator,
    resolveProps: (
      { title, text, dimension, subdimensions, desercionData, source },
      baseUrl,
    ) => ({
      title,
      text,
      dimension,
      source,
      subdimensions: subdimensions ?? [],
      data: desercionData ?? [],
      yAxisLabel: '%',
      csvPath: base(baseUrl, 'education_desercion.csv'),
    }),
  },
  repitencia: {
    component: DSSIndicator,
    resolveProps: (
      { title, text, dimension, subdimensions, repitenciaData, source },
      baseUrl,
    ) => ({
      title,
      text,
      dimension,
      source,
      subdimensions: subdimensions ?? [],
      data: repitenciaData ?? [],
      yAxisLabel: '%',
      csvPath: base(baseUrl, 'education_repitencia.csv'),
    }),
  },
  'prevision-social': {
    component: StratifiedIndicator,
    resolveProps: (
      { title, text, dimension, subdimensions, previsionSocialData, source },
      baseUrl,
    ) => ({
      title,
      text,
      dimension,
      source,
      subdimensions: subdimensions ?? [],
      data: previsionSocialData ?? [],
      stratifiers: ['regimen'],
      yAxisLabel: '%',
      csvPath: base(baseUrl, 'health_insurance.csv'),
    }),
  },
}
